config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 5, maximum: 20 }
  validates :description, presence: true, length: { minimum: 10, maximum: 50 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, flash: { success: 'Article was successfully created.'} }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, flash: { success: 'Article was successfully updated.' } }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, flash: { danger: 'Article was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only delete of edit your own article!"
        redirect_to root_path
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user %>,
                               <%= time_ago_in_words(article.created_at) %> ago,
                               last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>
        <div class="article-actions">
          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete this article', article_path(article), method: :delete,
                                              data: { confirm: "Are you sure?" },
                                              class: "btn btn-xs btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-md-12">

    <%= form_with(model: article, local: true, html: {class: "form-horizontal", role: "form"}) do |form| %>

      <%= render "shared/errors", model: article %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= form.label :title %>
        </div>
        <div class="col-sm-8">
          <%= form.text_field :title, class: "form-control", placeholder: "Article's title", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= form.label :description %>
        </div>
        <div class="col-sm-8">
          <%= form.text_area :description, rows: 10, class: "form-control", placeholder: "Article's body", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>

    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'Cancel request and return to articles listing', articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1 align="center">Articles</h1>

<div align="center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
  <ul class="listing">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li><small><%= pluralize(@article.user.articles.count, 'article') if @article.user.articles %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <%= simple_format(@article.description) %>
  <div class="article-actions">

  </div>
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to 'Delete this article', article_path(@article), method: :delete,
                                      data: { confirm: "Are you sure?" },
                                      class: "btn btn-xs btn-danger" %>
  <% end %>
  <%= link_to 'View all articles', articles_path, class: "btn btn-xs btn-success" %>
</div>